#define TILE_EMPTY 0
#define TILE_WATER -1

#define TILE_VENDEUR_GRAINE -50
#define TILE_ACHETEUR_PLANTE -51
#define TILE_ACHETEUR_POISSON -52

#define TILE_ENTER_HOUSE -10
#define TILE_EXIT_HOUSE -11

#define TILE_PNJ -20

#define TILE_CRABE -24
#define TILE_PY -25
#define TILE_RISETTE -26
#define TILE_SERGE -27

#define TILE_FARMLAND 33

#define TILE_ENTER_CAVE 40
#define TILE_EXIT_CAVE -41

#define TILE_A 8

#define TILE_LIVRE_SPAWN 60
#define TILE_LIVRE_HOUSE 61
#define TILE_LIVRE_FARM 62
#define TILE_LIVRE_FISHING 63
#define TILE_LIVRE_FOREST 64
#define TILE_LIVRE_BEACH 65
#define TILE_LIVRE_CAVE 66
#define TILE_LIVRE_MARKET 67
#define TILE_LIVRE_JSP 68

#define TILE_FISHING -30